In [1]:
#logistic reg, decision tree, KNN, naive bayes, SVM

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
data=pd.read_csv("weather.csv")

In [5]:
data

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0     11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3   
1     11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7   
2     11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3   
3     11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1   
4     11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6   
..          ...       ...      ...      ...       ...          ...       ...   
361  10/27/2008  Canberra      9.0     30.7       0.0          7.6      12.1   
362  10/28/2008  Canberra      7.1     28.4       0.0         11.6      12.7   
363  10/29/2008  Canberra     12.5     19.9       0.0          8.4       5.3   
364  10/30/2008  Canberra     12.5     26.9       0.0          5.0       7.1   
365  10/31/2008  Canberra     12.3     30.2       0.0          6.0      12.6   

    WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0            NW           30.0         SW  ...          29       1019.7   
1           ENE           39.0          E  ...          36       1012.4   
2            NW           85.0          N  ...          69       1009.5   
3            NW           54.0        WNW  ...          56       1005.5   
4           SSE           50.0        SSE  ...          49       1018.3   
..          ...            ...        ...  ...         ...          ...   
361         NNW           76.0        SSE  ...          15       1016.1   
362           N           48.0        NNW  ...          22       1020.0   
363         ESE           43.0        ENE  ...          47       1024.0   
364          NW           46.0        SSW  ...          39       1021.0   
365          NW           78.0         NW  ...          13       1009.6   

     Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0         1015.0         7         7     14.4     23.6         No      3.6   
1         1008.4         5         3     17.5     25.7        Yes      3.6   
2         1007.2         8         7     15.4     20.2        Yes     39.8   
3         1007.0         2         7     13.5     14.1        Yes      2.8   
4         1018.5         7         7     11.1     15.4        Yes      0.0   
..           ...       ...       ...      ...      ...        ...      ...   
361       1010.8         1         3     20.4     30.0         No      0.0   
362       1016.9         0         1     17.2     28.2         No      0.0   
363       1022.8         3         2     14.5     18.3         No      0.0   
364       1016.2         6         7     15.8     25.9         No      0.0   
365       1009.2         1         1     23.8     28.6         No      0.0   

     RainTomorrow  
0             Yes  
1             Yes  
2             Yes  
3             Yes  
4              No  
..            ...  
361            No  
362            No  
363            No  
364            No  
365            No  

[366 rows x 24 columns]

In [6]:
data["RainToday"]

0       No
1      Yes
2      Yes
3      Yes
4      Yes
      ... 
361     No
362     No
363     No
364     No
365     No
Name: RainToday, Length: 366, dtype: object

In [7]:
data["RainToday"].replace("Yes",1,inplace=True)

In [9]:
data["RainToday"].replace("No",0,inplace=True)

In [10]:
data

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0     11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3   
1     11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7   
2     11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3   
3     11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1   
4     11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6   
..          ...       ...      ...      ...       ...          ...       ...   
361  10/27/2008  Canberra      9.0     30.7       0.0          7.6      12.1   
362  10/28/2008  Canberra      7.1     28.4       0.0         11.6      12.7   
363  10/29/2008  Canberra     12.5     19.9       0.0          8.4       5.3   
364  10/30/2008  Canberra     12.5     26.9       0.0          5.0       7.1   
365  10/31/2008  Canberra     12.3     30.2       0.0          6.0      12.6   

    WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0            NW           30.0         SW  ...          29       1019.7   
1           ENE           39.0          E  ...          36       1012.4   
2            NW           85.0          N  ...          69       1009.5   
3            NW           54.0        WNW  ...          56       1005.5   
4           SSE           50.0        SSE  ...          49       1018.3   
..          ...            ...        ...  ...         ...          ...   
361         NNW           76.0        SSE  ...          15       1016.1   
362           N           48.0        NNW  ...          22       1020.0   
363         ESE           43.0        ENE  ...          47       1024.0   
364          NW           46.0        SSW  ...          39       1021.0   
365          NW           78.0         NW  ...          13       1009.6   

     Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0         1015.0         7         7     14.4     23.6          0      3.6   
1         1008.4         5         3     17.5     25.7          1      3.6   
2         1007.2         8         7     15.4     20.2          1     39.8   
3         1007.0         2         7     13.5     14.1          1      2.8   
4         1018.5         7         7     11.1     15.4          1      0.0   
..           ...       ...       ...      ...      ...        ...      ...   
361       1010.8         1         3     20.4     30.0          0      0.0   
362       1016.9         0         1     17.2     28.2          0      0.0   
363       1022.8         3         2     14.5     18.3          0      0.0   
364       1016.2         6         7     15.8     25.9          0      0.0   
365       1009.2         1         1     23.8     28.6          0      0.0   

     RainTomorrow  
0             Yes  
1             Yes  
2             Yes  
3             Yes  
4              No  
..            ...  
361            No  
362            No  
363            No  
364            No  
365            No  

[366 rows x 24 columns]

In [11]:
y=data.iloc[:,[21]].values

In [23]:
x=data.iloc[:,13:21].values

In [24]:
x

array([[6.8000e+01, 2.9000e+01, 1.0197e+03, ..., 7.0000e+00, 1.4400e+01,
        2.3600e+01],
       [8.0000e+01, 3.6000e+01, 1.0124e+03, ..., 3.0000e+00, 1.7500e+01,
        2.5700e+01],
       [8.2000e+01, 6.9000e+01, 1.0095e+03, ..., 7.0000e+00, 1.5400e+01,
        2.0200e+01],
       ...,
       [6.3000e+01, 4.7000e+01, 1.0240e+03, ..., 2.0000e+00, 1.4500e+01,
        1.8300e+01],
       [6.9000e+01, 3.9000e+01, 1.0210e+03, ..., 7.0000e+00, 1.5800e+01,
        2.5900e+01],
       [4.3000e+01, 1.3000e+01, 1.0096e+03, ..., 1.0000e+00, 2.3800e+01,
        2.8600e+01]])

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
scaler=StandardScaler()

In [35]:
x_train=scaler.fit_transform(x_train)

In [62]:
x_train

array([[-0.94000903, -0.80846783,  0.17415093, ..., -1.08745563,
        -0.1297867 ,  0.11783978],
       [-1.48257217, -1.15333579,  0.92560535, ..., -1.4575958 ,
        -1.21270244, -0.87332978],
       [ 0.76518942,  0.57100401,  0.60999449, ...,  0.0229649 ,
        -0.56644627, -0.24258552],
       ...,
       [-0.00990079, -0.69351185, -0.08134357, ..., -1.08745563,
        -0.91577393, -0.39276272],
       [-0.00990079,  0.85839397, -0.33683807, ..., -1.08745563,
        -1.3524335 , -1.63923354],
       [-1.71509924, -1.55568175,  0.4747327 , ..., -0.34717527,
         1.35485585,  2.0250903 ]])

In [36]:
x_test=scaler.fit_transform(x_test)

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
from sklearn.svm import SVC

In [31]:
from sklearn.naive_bayes import GaussianNB

In [32]:
log=LogisticRegression()
dec=DecisionTreeClassifier()
knn=KNeighborsClassifier()
sv=SVC(kernel="linear")
nav=GaussianNB()

In [37]:
log.fit(x_train,y_train)

c:\Users\GaneshKarbhari\.conda\envs\summ_env\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [38]:
dec.fit(x_train,y_train)

DecisionTreeClassifier()

In [39]:
knn.fit(x_train,y_train)

c:\Users\GaneshKarbhari\.conda\envs\summ_env\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [40]:
sv.fit(x_train,y_train)

c:\Users\GaneshKarbhari\.conda\envs\summ_env\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [41]:
nav.fit(x_train,y_train)

c:\Users\GaneshKarbhari\.conda\envs\summ_env\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [44]:
log_pred=log.predict(x_test)
log_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [45]:
dec_pred=dec.predict(x_test)
dec_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0], dtype=int64)

In [46]:
knn_pred=knn.predict(x_test)
knn_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [47]:
sv_pred=sv.predict(x_test)
sv_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [48]:
nav_pred=nav.predict(x_test)
nav_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0], dtype=int64)

In [49]:
from sklearn.metrics import confusion_matrix

In [52]:
log_mat=confusion_matrix(y_test,log_pred)
log_mat

array([[70,  1],
       [13,  8]], dtype=int64)

In [57]:
70+8

78

In [53]:
dec_mat=confusion_matrix(y_test,dec_pred)
dec_mat

array([[63,  8],
       [12,  9]], dtype=int64)

In [58]:
63+9

72

In [54]:
knn_mat=confusion_matrix(y_test,knn_pred)
knn_mat

array([[70,  1],
       [15,  6]], dtype=int64)

In [59]:
70+6

76

In [55]:
sv_mat=confusion_matrix(y_test,sv_pred)
sv_mat

array([[71,  0],
       [19,  2]], dtype=int64)

In [60]:
71+2

73

In [56]:
nav_mat=confusion_matrix(y_test,nav_pred)
nav_mat

array([[68,  3],
       [11, 10]], dtype=int64)

In [61]:
68+10

78